package routing

import (
	"aura/config"
	"aura/logging"
	routes_auth "aura/routing/auth"
	routes_base "aura/routing/base"
	routes_config "aura/routing/config"
	routes_db "aura/routing/database"
	routes_download "aura/routing/download"
	routes_images "aura/routing/images"
	routes_jobs "aura/routing/jobs"
	routes_labels_tags "aura/routing/labels-tags"
	routes_logging "aura/routing/logging"
	routes_ms "aura/routing/mediaserver"
	routes_plex "aura/routing/mediaserver/plex"
	routes_mediux "aura/routing/mediux"
	"aura/routing/middleware"
	routes_search "aura/routing/search"
	routes_sonarr_radarr "aura/routing/sonarr-radarr"
	routes_validation "aura/routing/validation"
	"aura/utils/httpx"
	"net/http"

	_ "aura/api-docs" // generated by swag init

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/jwtauth/v5"
	httpSwagger "github.com/swaggo/http-swagger"
)

func AddRoutes(r *chi.Mux) {
	// If the config is not valid, only allow access to the /onboarding routes
	if !(config.Loaded && config.Valid) {
		logging.LOGGER.Warn().Timestamp().Bool("loaded", config.Loaded).Bool("valid", config.Valid).Msg("Configuration invalid or not loaded, adding onboarding routes only")
		addOnboardingRoutes(r)
		return
	} else {
		logging.LOGGER.Info().Timestamp().Msg("Configuration loaded and valid, adding full routes")
	}

	// Initialize Token Auth
	secret, Err := routes_auth.GetTokenAuthSecret()
	if Err.Message != "" {
		logging.LOGGER.Error().Timestamp().Msg("Failed to get JWT Token Auth Secret: " + Err.Message)
	} else {
		routes_auth.SetTokenAuth(jwtauth.New("HS256", []byte(secret), nil))
		logging.LOGGER.Info().Timestamp().Msg("JWT Token Auth initialized successfully")
	}

	// Swagger Docs Route
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	// Base Routes
	r.Get("/", routes_base.HealthCheck)
	r.Get("/health", routes_base.HealthCheck)

	r.Route("/api", func(r chi.Router) {
		///////////////////
		// Public Routes
		//////////////////

		// Login - Obtain JWT Token
		r.Post("/login", routes_auth.Login)

		// Search - Public Search Endpoint (Media Items, Saved Sets and MediUX Users)
		r.Get("/search", routes_search.Search)

		// Sonarr Webhook Routes - Public since Sonarr/Radarr need to access it without authentication
		r.Post("/sonarr/webhook", routes_sonarr_radarr.SonarrWebhookHandler)

		/////////////////////
		// Protected Routes
		///////////////////
		r.Group(func(r chi.Router) {
			// Use JWT Auth Middleware
			r.Use(jwtauth.Verifier(routes_auth.TokenAuth))
			r.Use(middleware.Authenticator)

			// Config Routes
			r.Route("/config", func(r chi.Router) {
				r.Get("/", routes_config.Status)
				r.Post("/", routes_config.Update)
				r.Patch("/", routes_config.Reload)
			})

			// Jobs Routes
			r.Route("/jobs", func(r chi.Router) {
				r.Get("/", routes_jobs.GetAllJobs)
				// r.Post("/run/refresh-media-items-collections", StartRefreshMediaItemsCollectionsJobHandler)
				// r.Post("/run/refresh-mediux-users", StartRefreshMediuxUsersJobHandler)
				// r.Post("/run/check-mediux-site-link", StartCheckMediuxSiteLinkJobHandler)
				// r.Post("/run/check-rating-key-changes", StartCheckForRatingKeyChangesJobHandler)
			})

			// Database Routes
			r.Route("/db", func(r chi.Router) {
				r.Get("/", routes_db.GetAllItems)
				r.Post("/", routes_db.AddItem)
				r.Patch("/", routes_db.UpdateItem)
				r.Delete("/", routes_db.DeleteItem)
				r.Patch("/ignore", routes_db.IgnoreItem)
				r.Patch("/ignore/stop", routes_db.StopIgnoringItem)
				r.Post("/force-check", routes_download.AutoDownloadForceCheck)
			})

			// Download Routes
			r.Route("/download", func(r chi.Router) {
				// Download
				r.Post("/image/item", routes_download.DownloadImage)
				r.Post("/image/collection", routes_download.DownloadCollectionImage)

				// Download Queue Routes
				r.Route("/queue", func(r chi.Router) {
					r.Get("/", routes_download.QueueGetStatus)
					r.Get("/item", routes_download.QueueGetItems)
					r.Post("/item", routes_download.QueueAddItem)
					r.Delete("/item", routes_download.QueueRemoveItem)
				})
			})

			// Image Routes
			r.Route("/images", func(r chi.Router) {
				r.Get("/media/item", routes_images.GetMediaItemImage)
				r.Get("/media/collection", routes_images.GetCollectionItemImage)
				r.Get("/mediux/item", routes_images.GetMediuxImage)
				r.Get("/mediux/avatar", routes_images.GetMediuxAvatarImage)
				r.Delete("/temp", routes_images.DeleteTempImages)
			})

			// Labels & Tags Route
			r.Post("/labels-tags", routes_labels_tags.ApplyLabelsTags)

			// Logging Routes
			r.Route("/logs", func(r chi.Router) {
				r.Get("/", routes_logging.GetLogContent)
				r.Delete("/", routes_logging.ClearLogs)
			})

			// Media Server Routes
			r.Route("/mediaserver", func(r chi.Router) {
				r.Get("/libraries", routes_ms.GetLibrarySections)
				r.Post("/libraries/options", routes_ms.GetLibrarySectionOptions)
				r.Get("/library/items", routes_ms.GetLibrarySectionItems)
				r.Get("/item", routes_ms.GetMediaItemDetails)
				r.Get("/collections", routes_ms.GetMovieCollections)
				r.Get("/collections/item", routes_ms.GetAllCollectionChildrenItems)
				r.Patch("/rate", routes_ms.RateMediaItem)
				r.Post("/refresh", routes_ms.RefreshMediaItemMetadata)
			})

			// Plex OAuth Routes
			r.Get("/oauth/plex", routes_plex.GetPlexPinAndID)
			r.Post("/oauth/plex", routes_plex.CheckPlexPin)

			// MediUX Routes
			r.Route("/mediux", func(r chi.Router) {
				r.Get("/user", routes_mediux.GetUserFollowingAndHiding)
				r.Get("/set", routes_mediux.GetSetByID)
				r.Get("/sets/item", routes_mediux.GetItemSets)
				r.Get("/sets/user", routes_mediux.GetUserSets)
			})

			// Validation Routes
			r.Route("/validate", func(r chi.Router) {
				r.Post("/mediux", routes_validation.ValidateMediuxInfo)
				r.Post("/mediaserver", routes_validation.ValidateMediaServerInfo)
				r.Post("/sonarr", routes_validation.ValidateSonarrRadarrInfo)
				r.Post("/radarr", routes_validation.ValidateSonarrRadarrInfo)
				r.Post("/notifications", routes_validation.SendTestNotification)
			})
		})
	})
}

func addOnboardingRoutes(r *chi.Mux) {

	// Base Routes
	r.Get("/", routes_base.HealthCheck)
	r.Get("/health", routes_base.HealthCheck)

	r.Route("/api", func(r chi.Router) {
		///////////////////
		// Public Routes
		//////////////////

		// Config Routes
		r.Route("/config", func(r chi.Router) {
			r.Get("/", routes_config.Status)
			r.Post("/", routes_config.Update)
		})

		// Plex OAuth Routes
		r.Get("/oauth/plex", routes_plex.GetPlexPinAndID)
		r.Post("/oauth/plex", routes_plex.CheckPlexPin)

		// Logging Routes
		r.Route("/logs", func(r chi.Router) {
			r.Get("/", routes_logging.GetLogContent)
			r.Delete("/", routes_logging.ClearLogs)
		})

		r.Post("/mediaserver/libraries/options", routes_ms.GetLibrarySectionOptions)

		// Validation Routes
		r.Route("/validate", func(r chi.Router) {
			r.Post("/mediux", routes_validation.ValidateMediuxInfo)
			r.Post("/mediaserver", routes_validation.ValidateMediaServerInfo)
			r.Post("/sonarr", routes_validation.ValidateSonarrRadarrInfo)
			r.Post("/radarr", routes_validation.ValidateSonarrRadarrInfo)
			r.Post("/notifications", routes_validation.SendTestNotification)
			//r.Post("/database", routes_mediux.ValidateDatabaseInfo)
		})

		// Finalize Onboarding Route
		r.Post("/onboarding/finalize", func(w http.ResponseWriter, r *http.Request) {
			ctx, ld := logging.CreateLoggingContext(r.Context(), r.URL.Path)
			logAction := ld.AddAction("Finalize Onboarding", logging.LevelInfo)
			ctx = logging.WithCurrentAction(ctx, logAction)

			if !(config.Loaded && config.Valid) {
				logAction.SetError("Configuration is not valid or not loaded", "", nil)
				ld.Status = logging.StatusError
				httpx.SendResponse(w, ld, nil)
				return
			}

			triggered := false
			onboardingFinalizeOnce.Do(func() {
				triggered = true
				if OnboardingComplete != nil {
					logging.LOGGER.Info().Timestamp().Msg("Onboarding finalized, executing OnboardingComplete function")
					go OnboardingComplete()
				}
			})

			httpx.SendResponse(w, ld, map[string]any{
				"onboarding_finalized": triggered,
			})
		})
	})
}
