name: Docker Image CI and Release for Poster Setter

on:
    push:
        branches: ["master"]
        paths:
            - "backend/**"
            - "frontend/**"

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Extract Version
              id: extract_version
              run: |
                  if [[ -f VERSION.txt ]]; then
                    echo "VERSION=$(cat VERSION.txt)" >> $GITHUB_ENV
                  else
                    echo "VERSION=dev" >> $GITHUB_ENV
                  fi

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.PAT }}

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build Docker image
              run: |
                  docker buildx build . \
                    --platform linux/amd64,linux/arm64 \
                    --build-arg VERSION=${{ env.VERSION }} \
                    --tag ghcr.io/xmoosex/poster-setter:latest \
                    --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/poster-setter:latest \
                    --tag ghcr.io/xmoosex/poster-setter:${{ env.VERSION }} \
                    --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/poster-setter:${{ env.VERSION }} \
                    --push
