name: Docker Image CI and Release for Poster Setter

on:
    push:
        branches: ["master"]
        paths:
            - "backend/**"
            - "frontend/**"

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Git
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.PAT }}

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build Docker image
              run: |
                  docker buildx build . \
                    --platform linux/amd64,linux/arm64 \
                    --tag ghcr.io/xmoosex/poster-setter:latest \
                    --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/poster-setter:latest \
                    --push

            - name: Push Docker images to GHCR
              run: |
                  docker push ghcr.io/xmoosex/poster-setter:latest

            - name: Push Docker images to Docker Hub
              run: |
                  docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/poster-setter:latest
