# .github/workflows/poster-setter.yml
name: Docker Image CI and Release for Poster Setter

on:
    push:
        branches: ["master"]
        paths:
            - "backend/**"
            - "frontend/**"

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Git
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"

            - name: Extract and bump version
              id: version
              run: |
                  latest=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1 || echo "v0.0.0")
                  echo "Latest tag: $latest"
                  IFS='.' read -r major minor patch <<< "${latest#v}"
                  new_version="v$major.$minor.$((patch+1))"
                  echo "new_version=$new_version" >> $GITHUB_OUTPUT

            - name: Create Git tag
              run: |
                  git tag ${{ steps.version.outputs.new_version }}
                  git push origin ${{ steps.version.outputs.new_version }}

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.PAT }}

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build Docker image
              run: |
                  docker build . \
                    --build-arg VERSION=${{ steps.version.outputs.new_version }} \
                    --tag ghcr.io/xmoosex/poster-setter:latest \
                    --tag ghcr.io/xmoosex/poster-setter:${{ steps.version.outputs.new_version }} \
                    --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/poster-setter:latest \
                    --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/poster-setter:${{ steps.version.outputs.new_version }}

            - name: Push Docker images to GHCR
              run: |
                  docker push ghcr.io/xmoosex/poster-setter:latest
                  docker push ghcr.io/xmoosex/poster-setter:${{ steps.version.outputs.new_version }}

            - name: Push Docker images to Docker Hub
              run: |
                  docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/poster-setter:latest
                  docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/poster-setter:${{ steps.version.outputs.new_version }}

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ steps.version.outputs.new_version }}
                  name: Release ${{ steps.version.outputs.new_version }}
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
