# .github/workflows/poster-setter.yml
name: Docker Image CI for Poster Setter
on:
    push:
        branches: ["master"]
        paths:
            - "backend/**"
            - "frontend/**"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Step 1: Checkout the code
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Log in to GitHub Container Registry (ghcr.io)
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.PAT }}

            # Step 3: Build the Docker image
            - name: Build Docker image
              run: docker build ./ --tag ghcr.io/xmoosex/poster-setter:latest

            # Step 4: Push the Docker image
            - name: Push Docker image
              run: docker push ghcr.io/xmoosex/poster-setter:latest
